apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: saz13cn9c-nodejs 
  janus-idp.io/tekton: saz13cn9c-nodejs
  backstage.io/kubernetes-id: saz13cn9c-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: saz13cn9c-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  