apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: saz13cn9c-nodejs
  janus-idp.io/tekton: saz13cn9c-nodejs
  backstage.io/kubernetes-id: saz13cn9c-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: saz13cn9c-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
